// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Perfumaria.API.Infraestrutura.Dados;

#nullable disable

namespace Perfumaria.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Perfumaria.API.Dominio.Entidades.NotaOlfativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("FAMILIA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("T_PRF_NOTAS_OLFATIVAS", (string)null);
                });

            modelBuilder.Entity("Perfumaria.API.Dominio.Entidades.Perfume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO_LANCAMENTO");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("GENERO");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MARCA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Preco")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("PRECO");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VOLUME_ML");

                    b.HasKey("Id");

                    b.ToTable("T_PRF_PERFUMES", (string)null);
                });

            modelBuilder.Entity("Perfumaria.API.Dominio.Entidades.PerfumeNota", b =>
                {
                    b.Property<int>("PerfumeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERFUME_ID");

                    b.Property<int>("NotaOlfativaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTA_OLFATIVA_ID");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("POSICAO");

                    b.HasKey("PerfumeId", "NotaOlfativaId");

                    b.HasIndex("NotaOlfativaId");

                    b.ToTable("T_PRF_PERFUME_NOTA", (string)null);
                });

            modelBuilder.Entity("Perfumaria.API.Dominio.Entidades.PerfumeNota", b =>
                {
                    b.HasOne("Perfumaria.API.Dominio.Entidades.NotaOlfativa", "NotaOlfativa")
                        .WithMany("Perfumes")
                        .HasForeignKey("NotaOlfativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Perfumaria.API.Dominio.Entidades.Perfume", "Perfume")
                        .WithMany("Notas")
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaOlfativa");

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("Perfumaria.API.Dominio.Entidades.NotaOlfativa", b =>
                {
                    b.Navigation("Perfumes");
                });

            modelBuilder.Entity("Perfumaria.API.Dominio.Entidades.Perfume", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
